### ISSUE TITLE
Start from 0!

### ISSUE THREAD

**Issue by kitlith** [kitling/undertale_techdemo#2]
The room numbers currently start from 1. This will probably wait until stuff before Home is added, or until I look at the room numbers that the original game uses.

... BAH! Undertale starts from 1, and 1-3 are error rooms. 4 is where it actually starts...

When I get around to doing this, I'll just subtract one from the ID loaded from the save.

Oh, right, that would wait until I load saves.

**Comment by kitlith** [comment]
Sort of fixed by commit fd4b2da4ad8f52d4a915b427d43c05de37295ff4, but it doesn't add the error rooms or whatever. So, leaving this open for now.

This will truly be fixed when we start with the rooms that undertale actually does.

**Comment by ghost** [comment]
Man!!! I love this Homebrew!

**Comment by kitlith** [comment]
... Quick note, that comment has nothing to do with this issue. I'd like to keep issues to actual issues and discussion of them.

That said, thank you! And remember, I wasn't the one who started this, I merely continued it. :P

**Comment by kitlith** [comment]
closing the issue since I'm no longer working on this.
